version: '3.8'
services:


  fresh-near-me-rest:
    container_name: fresh-near-me-rest-container
    build:
      context: modules/backend-api/server
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
