name: Java CI

on:
  push:
    branches:
      - develop_docker

jobs:
  build:

    runs-on: ubuntu-latest
    environment: fresh-near-me-environment

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set executable permissions for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Build and push Docker image
#        run: |
#          docker build -t fresh-near-me-rest:latest -f ../../modules/backend-api/server/Dockerfile .
#          docker push fresh-near-me-rest:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./modules/backend-api/server
          file: ./modules/backend-api/server/Dockerfile
          push: true
          tags: fresh-near-me-rest:latest